apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: example-ingress-class
spec:
  controller: nginx.org/ingress-controller
  parameters:
    apiGroup: networking.k8s.io
    kind: IngressClassParametersReference
    name: example-ingress-parameters
