apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: example-mutating-webhook
webhooks:
  - name: mutating-webhook.example.com
    clientConfig:
      service:
        name: webhook-service
        namespace: webhook-namespace
        path: /mutate
      caBundle: Y2FCdW5kbGU= # Base64-encoded CA certificate
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    failurePolicy: Ignore
    admissionReviewVersions: ["v1"]
    sideEffects: None
