name: Kubescape scanning for misconfigurations
on: [push, pull_request]
jobs:
  kubescape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ls ./templates
      - uses: kubescape/github-action@main
        continue-on-error: true
        with:
          format: sarif
          files: ./templates
          outputFile: results.sarif
          # # Optional: Specify the Kubescape cloud account ID
          # account: ${{secrets.KUBESCAPE_ACCOUNT}}
          # # Optional: Scan a specific path. Default will scan the whole repository
          # files: "examples/*.yaml"
      - run: head -n 50 results.sarif
      - name: Upload Kubescape scan results to Github Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
