name: Kubescape scan manifest files
run-name: Scan manifest files
on: [push]
jobs:
  kubescape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: kubescape/github-action@main
        continue-on-error: true
        name: Kubescape scan
        with:
          format: sarif
          outputFile: results
      - uses: github/codeql-action/upload-sarif@v3
        name: Upload scan results to Github Code Scanning
        with:
          sarif_file: results.sarif
